hash-format = "sha256"

[[files]]
file = "mods/accurate-block-placement-reborn.pw.toml"
hash = "5d1b0d0fc0c0422d25b54e0bd7a76a7733967278c7691830fb53fb0879ad4884"
metafile = true

[[files]]
file = "mods/additional-structures.pw.toml"
hash = "92d14d6894accfa0235501625b7170ec9414131e911696b77da7d7d874b147e9"
metafile = true

[[files]]
file = "mods/adorabuild-structures.pw.toml"
hash = "4c022e6ac4a4277393aba466a204311379b79754939ca83a66532d55a8b86ac3"
metafile = true

[[files]]
file = "mods/advancements-reloaded.pw.toml"
hash = "6e804a5e09aee7198f1d84082bf942361e5876242829060961da84b395772961"
metafile = true

[[files]]
file = "mods/amplified-nether.pw.toml"
hash = "de2cd31fd6add0bdd12a7ff2e9d6ca39dead13907575f19bb1901fb2b56789d8"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "c22ebc9646c063a5c53acae5b49a0b54f8b21500ecc79a9c52b142775512b2d6"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "832691489ab19e2f0a4b81b77c143a8dceb5f3f395cdee96bcddd893fb01b363"
metafile = true

[[files]]
file = "mods/auto-harvest.pw.toml"
hash = "ef33f33e770c954fc86ff3c103f40b50ee856fa2e3708aff02408b4246c6100e"
metafile = true

[[files]]
file = "mods/awesome-dungeon-edition-ocean.pw.toml"
hash = "8e05dff9c6071655cf8cb4319c44fe7bf9b11cec956846e3236c81db28a9f32d"
metafile = true

[[files]]
file = "mods/awesome-dungeon-nether.pw.toml"
hash = "c876d57407afded28e3707bace8faaead85178363cada5c80ac500dac9a8676f"
metafile = true

[[files]]
file = "mods/awesome-dungeon.pw.toml"
hash = "5f057cca9799c1c60d3344bffa97a15ee4285a3b3d8a04d6a337225cf89995f0"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "e15eb47019c1372379817862e66999aa3eb4dedc5661fae902147b15201c8054"
metafile = true

[[files]]
file = "mods/better-village.pw.toml"
hash = "0ff89d8ed48d75dee5a3458e79b9156a550eb644caf42d6d21c7a5002d49e976"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "fc0c787d043f2233fd45c724e80020ecf1e1e0e454ba43ecb8107de74a20e1e6"
metafile = true

[[files]]
file = "mods/bluemap-offline-player-markers-(fabric).pw.toml"
hash = "5f55ee3cd66c5367efea9d3b3e7c7311cfa563c7db668b9f621d76afac4cb086"
metafile = true

[[files]]
file = "mods/bluemap-sign-markers.pw.toml"
hash = "4ea18a9dd36c9cb4cae2dc353eb0c87ac5d8ddd73c2c382ec7319904e46fe056"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "950139b43bd4634848c39bbe340b2b69a096ddf856080e75cd4ef96899d04a71"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "9b5595b414f281b4f30c53751d0a0fb213ea4e70b94baf3e249886585f1afefb"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "d3b1615401954ddd0afdfadd4e0ea6c06a1c84264a872774546ccf53666355a3"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "315bafd24f8ba8c74db38cdd35148cb7be59d89d92a1e90c0c41d7093a9deda9"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
hash = "95a409d7794c80fd1f5bab4ad082a8b165a678435c32948b46597c157834a6db"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "f949303590e17c58d654645c7a56c6c113d2d12ee54fdb98c284ae22d98cbe97"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "1128e1194453ee08fd9cad27630786f0bc18d99fb3b5e1e5f87714d7c1fe489a"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "667a35bb32cf1eb47a1837473922c8391a4630cf852f7ae2d5405604e8113ca7"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
hash = "c78df4f53cff3099497dcad7e1683135b7327d8ebd7489b6bf301103684fd949"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
hash = "fdb80dded868a59bab7ecbd9e78139670e2f3fc0e60775e1873938279efa3881"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "547fcb6481c2cf682b9de98f0a719d27f0ba896d7b06076f2135f2abd470aea6"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-ancient-city-overhaul.pw.toml"
hash = "0a61218868f67bf0ecdc9463c0e932162f09627adaaf5791e7191ace3e2a40cc"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-desert-temple-overhaul.pw.toml"
hash = "3450d91922ee841907dc8a2c2df9521cc5f63bf8ca69527087cc8c2c9451e226"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-end-castle-standalone.pw.toml"
hash = "778333a87b61cbcad7c307626d2764c5347fb204ee8fb3a8e96de75534258499"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-jungle-temple-overhaul.pw.toml"
hash = "6d19dddfb651a51fb94f146aa3b020aaa1d94469a368e78f57e745766a4d92e4"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-nether-fortress-overhaul.pw.toml"
hash = "ab0784d394d2ba6279ac632091aea31548cb1c05962cda524a36ac25869ba858"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-ocean-monument-overhaul.pw.toml"
hash = "2558339dade0e6e608363cdf3b72d2348f68d1f70882f4b1044d30497e8e50e4"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-pillager-outpost-overhaul.pw.toml"
hash = "df30bc54a8efa228d50d8a2c12e2752d3d50d3023f691c97b7c154036d1bb649"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-stronghold-overhaul.pw.toml"
hash = "bfeed9b89e4dff5a0f38e5cd7df0dee85a76db785574a2049a43b3f53a5cf42b"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-swamp-hut-overhaul.pw.toml"
hash = "da7d642b271e913765b14350054bcd0ce3b735bc3bd983b0a96377f7ec8dbb57"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "f5f0c6eb7dac137337317f104664381a864465e912087195505e3abb3b7b79bc"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
hash = "57a4c805677d9384c2985750615876572f56245b224084a1c66fb0c9b7ed238e"
metafile = true

[[files]]
file = "mods/epic-structures-villages.pw.toml"
hash = "c4ea287d24b4f4bd4c5e63070282065cb8e576ceddb6441a9f4ea88daa3dee88"
metafile = true

[[files]]
file = "mods/epic-structures-witch-huts.pw.toml"
hash = "705ad88e39df2a1e4fb511e19db2a9208f2296215dc2eaf8382ff1896d0b3311"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "d246630b697cddeda5d6a3215b078f49d663c079b71acdbbdd1c50eb83505ca9"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "c777d80ae30744d7d08babc5ed5bb6fcc7e8b979eeb1d3f52fe1ca00c0036b8c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "54e3cc9a3c2a05cc879ffda7f4c97a89be0b648421d6c8fe92e2d3e5761abf20"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "ea40c2f09338485de8ed94ae09c84182e2544ff166e5d9a33b9be8ea13d3f750"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "1e4e37a781f247c943ccfd23d3a6cdf317297a4ef43743fe5141d1f16e81876b"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "46b9d33dcb834d415bce5a41b649363379563f1003c6021da9cd6d454c10e0e0"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e5506cea71f62e147a45e6c72a55a430fce5937024f648c819c15dc14b500462"
metafile = true

[[files]]
file = "mods/library-ferret.pw.toml"
hash = "255e7276fbc2e28a796666639d0ef8496be02d522c28a63f3a0cf74a129a57a2"
metafile = true

[[files]]
file = "mods/light-machine.pw.toml"
hash = "6d1b4c3561ed8789ca4a56ce37fc8c1350e05a185711226239e7a764971183b5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a63765eb780a36cd968e2777d2c20bea5e5ca3ccdd920e64964e3746cf2a7f0d"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "b1aa32235b6d929f8ac67bea98b72e907bd8548d3c6e60bb27cd733d7ca03283"
metafile = true

[[files]]
file = "mods/magnum-torch.pw.toml"
hash = "dd1b32338b9fab6b9dc14b72cc1c357a7ce33b61a9ae863f1c10df8d3922c2f0"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "87c4d42219d3aea70af7aa016e0e4bdfac94d2a4ece9e719e8e84e9203735300"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
hash = "02136827d47b338d4f1c897cfa1eb4d92bd0f5dfc5300875c9737390ffcc529a"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "079e6b85da3a1aa67c46b4b1f48c3e229a54865e22d4b2e2e55cc94689cc4e89"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "be165c98a6b6878a158d7d0606f68bf2c8e59cde8b95455d4b872c82f0041fc8"
metafile = true

[[files]]
file = "mods/mmv-moogs-missing-villages.pw.toml"
hash = "d62031d06050a4f271149c72b484a6fab05afc17845bdd044018c764ce243055"
metafile = true

[[files]]
file = "mods/mns-moogs-nether-structures.pw.toml"
hash = "bee01d4388fcc23be892c81a5eff5b7bbf50e846a6d7088397a7a818ad459a0c"
metafile = true

[[files]]
file = "mods/mo-structures.pw.toml"
hash = "428756a3fa97fdc4d6ceee73bc20f660d698b3229907d34336b7072e90b3687e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6eea5e1db3dbca126b82f211bf0d2fcf2cf13097023fdef3dd668e48581a73d0"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "4a042e0eaa27b341b33f2a77464d728544b1ad179270ae0f5c091129f1a6c664"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "5c5a98c63fc8d7882eca391942741727f7c51c87fa5f48f6f91cebbd1d6e3e0f"
metafile = true

[[files]]
file = "mods/mss-moogs-soaring-structures.pw.toml"
hash = "3deba88dde4580fc49be3fa215a3b17e325c9c68f5b3a0185dc7639730bbb32b"
metafile = true

[[files]]
file = "mods/mtr-moogs-temples-reimagined.pw.toml"
hash = "1b818fad441e1474fd67189319be9db096262ca0fe119954d7a29fe218fb38c4"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "bf387fb939f9a4a7f0dbd45542c9681244785f8f0daf83eb3b7d3a9a33709ec6"
metafile = true

[[files]]
file = "mods/philips-ruins.pw.toml"
hash = "ed28427f76a5ea4d7ec604057bbd65ed6ea1ca1e0198c74553bf0e3dbbfb618b"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "0993352e081593fca386a8a4e6473ece541a27e018c8384239f27f79d73133a0"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "c8cc1d7e91aa70a842dad55a649bab3b0f899aa5a2fd191a3a4a44fc6e4e3005"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4019dc9d377028099ae87ffc5b03bd09deb284057a1e3b8910171837b2966266"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "0ebcac819db1ea71488bc30ee57ab0c7f65b6e9395890f52120d8700cacc6286"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "868381c35c3efe420910a3df2e843f28499090085456b789de14ab6a38ff1ff2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "3ef916454266cdbcbd3f517c53b1e27b360caa5266bf1b44d0d627aeab643516"
metafile = true

[[files]]
file = "mods/sparsestructures.pw.toml"
hash = "6030dfab1f098acfd8a817732b1a65cf6c3caa0f0134e0576f5c425639eb480c"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
hash = "5b59709d06cbe4ee6fb2f7dcca52d70d27315e918ec4f78db6b8893fa8c9ab72"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "9a107159ef78af626eec4f8455600c86e3df957e74e5950819f0c44dcb5beb33"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "a21afaf5777783244b77cd9b4333759bfa94ddd3ddc359f1a00355100430f177"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "a62ccb246536065446fe8f9bb92e4815f4d1c80040c73a8014a26691de1b0e3d"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "b59f4d3368c4e6fa4dd27fda4e9983aecababd81ee27e104084c77eefba83f49"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "e22d574139b2e480775ddf3258f879679d534ac1f6ffe68e64ff4408e024e6c7"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "03779db3c7cbf7d5853647c3e800880468f8aeffb4bc7be174bbb0e243b0ea1a"
metafile = true

[[files]]
file = "mods/trading-post.pw.toml"
hash = "744102a690f6226d481f0f0be9a21edf286c8caa6e06f4efc74954a12ae2eac0"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "3a3eac5ffe0a6299390ee43c0dcefacf1884164949ccbf32d9e862e4de4beecb"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "6f7958dff47cbd6a9d802d421b3f333e62652449e548cabf6d25da4c2db96566"
metafile = true

[[files]]
file = "mods/wits.pw.toml"
hash = "93c32a77add965852df10a20824efe70f59d779bc4f0f8a6a2e684cb47695e3f"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "06900344c9edbc5a0fa132fe75409fd6d2044bdf0becb9209ffae12962683362"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "d72a8ffcacdd19e6d71eccb4b112cf763bf75b2c438506e01ab0aa76e91c6325"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "f3b0dc8728401319a897b51835b2b65898dc3b769aa1f1ed0a1f513bd91c409a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ea0eb6ab539b43926503901694913866aa81a9a644cd3469080214a7ca785db2"
metafile = true
