name = "GG"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0490dec6b234c3f1b6e22fa4eefc1a933b7154deba011bb0d8c4c68a253129f5"

[versions]
fabric = "0.18.0"
minecraft = "1.21.8"
