name = "GG"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63dea6b7e879ac8cc6b64eba04ab2325029016c2713366c8070ac91f11526726"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
