name = "GG"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26a7a733c8dbe7e31f387ef39116a65124a4e1ed74598902b4a1a2cf3097336a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
