name = "GG"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "114d7e543de1914beaa2c92b9711c544aa9b3f7058bb215ad28b5a7699164fab"

[versions]
fabric = "0.18.0"
minecraft = "1.21.8"
