name = "GG"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c4522e20765acff1225c5a4a35cadf120ded1a57e38902cece3244151d26c80"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
