name = "GG"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f6ba01d5606417b9c71aa2e4766d99fe7d1c386208bfe9f25a11c4a567407c1"

[versions]
fabric = "0.18.0"
minecraft = "1.21.8"
