name = "GG"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e04f6686552b1506b6b03d2e7e5ec98524f6a5a1e2fe9feaf8b8d69f37ffb268"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
