name = "GG"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bfb370df8c18eadd180fee9d52fd7d9172e1800795fb9ec80538444627e7d1d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
